services:
  - type: web
    name: threads-backend
    env: python
    buildCommand: apt-get update && apt-get install -y libpq-dev && pip install -r requirements.txt
    startCommand: python src/main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.0
